### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by sbharadwajj** [ivclab/agegenderLMTCNN#6]
Hi, @Jia-HongHenryLee 
The model is taking too much time to predict the results.
I've used a separate mtcnn to detect it, and if an image has around 15 faces its taking 10secs to predict the age and gender. Is there a fix to this?
I've combined `multi_crop` and `multi_batch` and stacked it to a single tensor and sending the result as a  `Eg:(24,227,227,3) tensor for 2 faces.`  Is there a fix to this? Is there anyway of directly using the `bounding_boxes` obtained fro mtcnn instead of converting it to bytes etc?

**Comment by Jia-HongHenryLee** [comment]
@chichilicious  In the first prediction, the spending time is composed of initialization model time and prediction time, so you should not compute the time of the first prediction. You need to try to predict the same image 10 times continually and do not compute the time of 1st~5th predictions. Only utilizing the last the time of five predictions computes the mean computation time. 
If you want to predict more faces (e.g. 10 faces), you need to utilize the function of multi_batch. it will decrease the computation time. 
The function of multi_crop will make the one facial image becomes five facial images, so if you want to utilize it, you should combine it with the function of multi_batch.
In my code of android version, I directly utilize the bounding box predicted by MTCNN and use this facial image to predict the age and gender. I need time to prepare my code because some code can not release and I do not have free time recently.  Thank you very much.

**Comment by sbharadwajj** [comment]
Hi, but multi_batch also decreases the accuracy of the model compared to multi_crop. Yes. I have already combined multi_batch and multi_crop, but the run time is too slow. Okay sure, I will checkout the Android version of it.

**Comment by sbharadwajj** [comment]
Also, why are the images read as bytes and converted to JPEG? Is there a specific reason for this?

**Comment by Jia-HongHenryLee** [comment]
@chichilicious  because reading the images as bytes type can increase the processing time of image processing algorithms. 
You also can convert the images become PNG file format, not only JPEG file format.
Thank you very much.

**Comment by Jia-HongHenryLee** [comment]
@chichilicious because reading the images as bytes type can decrease the processing time of image processing algorithms.
You also can convert the images become PNG file format, not only JPEG file format.
Thank you very much.
